### ISSUE TITLE
egg配置完插件发送失败

### ISSUE THREAD

**Issue by i-apples** [alex-my/egg-full-email#3]
返回错误提示 
 connect ECONNREFUSED 127.0.0.1:25 undefined

**Comment by alex-my** [comment]
配置发我瞧瞧。





| |
alex_my
|
|
邮箱：alex_my@126.com
|

Signature is customized by Netease Mail Master

在2020年03月21日 18:29，驼兄 写道：

返回错误提示
connect ECONNREFUSED 127.0.0.1:25 undefined

**Comment by i-apples** [comment]
thanks，问题已经解决了
